---

- name: Mount and deploy docker image
  hosts: local
  roles:
    - { role: updatedockerfile, tags: ["updatedockerfile", "rebuildimage"]}

- name: Deployment script on server
  hosts: tag_Name_serveur_madu
  roles:
    - { role: installdocker, become: yes, tags: ["installdocker", "install+deploy"]}
    - { role: deploydockercompose, tags: ["deploydockercompose", "install+deploy", "rebuildimage"]}