---

- name: Create client docker image and push to docker hub
  docker_image:
    build:
      path: "{{ role_path }}/../../../../client"
      network: host
    name: madu_client
    repository: amauryfaveriel/madu-client
    tag: 1
    push: yes
    source: build

- name: Create back end docker image and push to docker hub
  docker_image:
    build:
      path: "{{ role_path }}/../../../../back-end"
      network: host
    name: madu_back-end
    repository: amauryfaveriel/madu_back-end
    tag: 1
    push: yes
    source: build

