---

- name: Update system packages
  apt:
    update_cache: yes
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Get Docker official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add pkg in apt repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker pkg
  apt:
    update_cache: yes
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    state: present

- name: Add user in docker group
  user:
    name: "{{ server_user_name }}"
    groups: docker

- name: Create directory for deployment
  file:
    path: /home/ubuntu/site
    state: directory
    owner: ubuntu
    group: docker
    mode: '0755'